# ./Taskfile.yaml
# See: https://taskfile.dev

version: "3"

tasks:
  generate:  ## Команда для генерации
    aliases: ## Алиасы команды, для простоты использования
      - gen
    desc: "Generate code from proto files"
    cmds:  ## Тут описываем необходимые bash-команды
      - protoc -I proto proto/*.proto --go_out=./api --go_opt=paths=source_relative --go-grpc_out=./api --go-grpc_opt=paths=source_relative